wX: Use template like strings
wasabee-project/Wasabee-IITC pull request #228
Opened 2021-05-01 12:30 UTC by le-jeu

Main idea is to be more generic: `wX(<NAME>, {placeholder1: value1,...})` allowing more elaborated strings.

Note: I found and removed some duplicates in the current locales.

2021-05-01 17:48 UTC, cloudkucooland commented
I like the concept. Thank you for this work.

2021-05-04 12:31 UTC, ruharen requested changes
I've tried to give consistency for the word 'name' in translation parameters, changing it to opName, agentName, etc, as needed. It also improves disambiguation for translators: "{name}??, name of what??" ;)

2021-05-04 12:31 UTC, ruharen commented on src/code/translations/french.json
> +  "SET_MCOMMENT": "Commentaire pour ce marqueur : {name}",
```suggestion
  "SET_MCOMMENT": "Commentaire pour ce marqueur : {portalName}",
```

2021-05-04 12:31 UTC, ruharen commented on src/code/translations/german.json
> +    "SET_MCOMMENT": "Setze Kommentar für Markierung: {name}",
```suggestion
    "SET_MCOMMENT": "Setze Kommentar für Markierung: {portalName}",
```

2021-05-04 12:31 UTC, ruharen commented on src/code/translations/italian.json
> +  "SET_MCOMMENT": "Imposta commento Marker: {name}",
```suggestion
  "SET_MCOMMENT": "Imposta commento Marker: {portalName}",
```

2021-05-04 12:31 UTC, ruharen commented on src/code/translations/spanish.json
> +  "SET_MCOMMENT": "Definir Comentario de Marcador {name}",
```suggestion
  "SET_MCOMMENT": "Definir Comentario de Marcador {portalName}",
```

2021-05-04 12:31 UTC, ruharen commented on src/code/translations/english.json
> +  "SET_PCOMMENT": "Set Portal Comment: {name}",
```suggestion
  "SET_PCOMMENT": "Set Portal Comment: {portalName}",
```

2021-05-04 12:31 UTC, ruharen commented on src/code/translations/filipino.json
> +    "SET_PCOMMENT": "Italaga ang commento sa Portal: {name}",
```suggestion
    "SET_PCOMMENT": "Italaga ang commento sa Portal: {portalName}",
```

2021-05-04 12:31 UTC, ruharen commented on src/code/translations/french.json
> +  "SET_PCOMMENT": "Entrer un commentaire pour ce portail : {name}",
```suggestion
  "SET_PCOMMENT": "Entrer un commentaire pour ce portail : {portalName}",
```

2021-05-04 12:31 UTC, ruharen commented on src/code/translations/german.json
> +    "SET_PCOMMENT": "Setze Kommentar für Portal: {name}",
```suggestion
    "SET_PCOMMENT": "Setze Kommentar für Portal: {portalName}",
```

2021-05-04 12:31 UTC, ruharen commented on src/code/translations/italian.json
> +  "SET_PCOMMENT": "Imposta commento Portale: {name}",
```suggestion
  "SET_PCOMMENT": "Imposta commento Portale: {portalName}",
```

2021-05-04 12:31 UTC, ruharen commented on src/code/translations/spanish.json
> +  "SET_PCOMMENT": "Definir Comentario de Portal {name}",
```suggestion
  "SET_PCOMMENT": "Definir Comentario de Portal {portalName}",
```

2021-05-04 12:31 UTC, ruharen commented on src/code/translations/english.json
> +  "TEAM_CREATED": "Team {name} created",
```suggestion
  "TEAM_CREATED": "Team {teamName} created",
```

2021-05-04 12:31 UTC, ruharen commented on src/code/translations/filipino.json
> +    "TEAM_CREATED": "Pangkat {name} nabuo",
```suggestion
    "TEAM_CREATED": "Pangkat {teamName} nabuo",
```

2021-05-04 12:31 UTC, ruharen commented on src/code/translations/french.json
> +  "TEAM_CREATED": "Équipe {name} créée",
```suggestion
  "TEAM_CREATED": "Équipe {teamName} créée",
```

2021-05-04 12:31 UTC, ruharen commented on src/code/translations/german.json
> +    "TEAM_CREATED": "Team {name} erstellt.",
```suggestion
    "TEAM_CREATED": "Team {teamName} erstellt.",
```

2021-05-04 12:31 UTC, ruharen commented on src/code/translations/english.json
> +  "COMPLETED BY": "Completed by {name}",
```suggestion
  "COMPLETED BY": "Completed by {agentName}",
```

2021-05-04 12:31 UTC, ruharen commented on src/code/translations/filipino.json
> +    "COMPLETED BY": "Nakumpleto ni {name}",
```suggestion
    "COMPLETED BY": "Nakumpleto ni {agentName}",
```

2021-05-04 12:31 UTC, ruharen commented on src/code/translations/french.json
> +  "COMPLETED BY": "Fait par {name}",
```suggestion
  "COMPLETED BY": "Fait par {agentName}",
```

2021-05-04 12:31 UTC, ruharen commented on src/code/translations/german.json
> +    "COMPLETED BY": "Abgeschlossen von {name}",
```suggestion
    "COMPLETED BY": "Abgeschlossen von {agentName}",
```

2021-05-04 12:31 UTC, ruharen commented on src/code/translations/italian.json
> +  "COMPLETED BY": "Completato da {name}",
```suggestion
  "COMPLETED BY": "Completato da {agentName}",
```

2021-05-04 12:31 UTC, ruharen commented on src/code/translations/spanish.json
> +  "COMPLETED BY": "Completado por {name}",
```suggestion
  "COMPLETED BY": "Completado por {agentName}",
```

2021-05-04 12:31 UTC, ruharen commented on src/code/translations/english.json
> +  "FAKED": "Faked: [{id}]",
```suggestion
  "FAKED": "Faked: [{portalId}]",
```

2021-05-04 12:31 UTC, ruharen commented on src/code/translations/french.json
> +  "FAKED": "Faux [{id}]",
```suggestion
  "FAKED": "Faux [{portalId}]",
```

2021-05-04 12:31 UTC, ruharen commented on src/code/translations/italian.json
> +  "FAKED": "Simulato: [{id}]",
```suggestion
  "FAKED": "Simulato: [{portalId}]",
```

2021-05-04 12:31 UTC, ruharen commented on src/code/translations/english.json
> +  "LOADING1": "Loading: [{guid}]",
```suggestion
  "LOADING1": "Loading: [{portalGuid}]",
```

2021-05-04 12:31 UTC, ruharen commented on src/code/translations/french.json
> +  "LOADING1": "Chargement: {guid}",
```suggestion
  "LOADING1": "Chargement: {portalGuid}",
```

2021-05-04 12:31 UTC, ruharen commented on src/code/translations/italian.json
> +  "LOADING1": "Caricamento: [{guid}]",
```suggestion
  "LOADING1": "Caricamento: [{portalGuid}]",
```

2021-05-04 12:31 UTC, ruharen commented on src/code/translations/english.json
> +  "DEFAULT OP NAME": "New Op: {name}",
```suggestion
  "DEFAULT OP NAME": "New Op: {opName}",
```

2021-05-04 12:31 UTC, ruharen commented on src/code/translations/filipino.json
> +    "DEFAULT OP NAME": "Bagong Op {name}",
```suggestion
    "DEFAULT OP NAME": "Bagong Op {opName}",
```

2021-05-04 12:31 UTC, ruharen commented on src/code/translations/french.json
> +  "DEFAULT OP NAME": "Opération {name}",
```suggestion
  "DEFAULT OP NAME": "Opération {opName}",
```

2021-05-04 12:31 UTC, ruharen commented on src/code/translations/german.json
> +    "DEFAULT OP NAME": "Neue Operation: {name}",
```suggestion
    "DEFAULT OP NAME": "Neue Operation: {opName}",
```

2021-05-04 12:31 UTC, ruharen commented on src/code/translations/spanish.json
> +  "DEFAULT OP NAME": "Nueva Op: {name}",
```suggestion
  "DEFAULT OP NAME": "Nueva Op: {opName}",
```

2021-05-04 12:31 UTC, ruharen commented on src/code/translations/italian.json
> +  "DEFAULT OP NAME": "Nuova Op: {name}",
```suggestion
  "DEFAULT OP NAME": "Nuova Op: {opName}",
```

2021-05-04 12:31 UTC, ruharen commented on src/code/translations/french.json
> +  "KNOWN_BLOCK": "Liens bloquants connus : {name}",
```suggestion
  "KNOWN_BLOCK": "Liens bloquants connus : {opName}",
```

2021-05-04 12:31 UTC, ruharen commented on src/code/translations/french.json
> +  "OP_CHECKLIST": "Operation Checklist: {name}",
```suggestion
  "OP_CHECKLIST": "Operation Checklist: {opName}",
```

2021-05-04 12:31 UTC, ruharen commented on src/code/translations/french.json
> +  "IMPORT_OP_TITLE": "Importer l'opération : {name}",
```suggestion
  "IMPORT_OP_TITLE": "Importer l'opération : {opName}",
```

2021-05-04 12:31 UTC, ruharen commented on src/code/dialogs/importDialog.js
> +      alert(wX("IMPORT_OP_SUCCESS", { name: importedOp.name }));
```suggestion
      alert(wX("IMPORT_OP_SUCCESS", { opName: importedOp.name }));
```

2021-05-04 12:31 UTC, ruharen commented on src/code/translations/english.json
> +  "IMPORT_OP_SUCCESS": "Imported Operation: {name} successfuly.",
```suggestion
  "IMPORT_OP_SUCCESS": "Imported Operation: {opName} successfuly.",
```

2021-05-04 12:31 UTC, ruharen commented on src/code/translations/french.json
> +  "IMPORT_OP_SUCCESS": "Importer l'opération : {name} Reussi.",
```suggestion
  "IMPORT_OP_SUCCESS": "Importer l'opération : {opName} Reussi.",
```

2021-05-04 12:31 UTC, ruharen commented on src/code/translations/german.json
> +    "IMPORT_OP_SUCCESS": "Importierte Operation: {name}. Erfolgreich.",
```suggestion
    "IMPORT_OP_SUCCESS": "Importierte Operation: {opName}. Erfolgreich.",
```

2021-05-04 12:31 UTC, ruharen commented on src/code/translations/french.json
> +  "PORTAL KEY LIST": "Clés du portail {name}",
```suggestion
  "PORTAL KEY LIST": "Clés du portail {portalName}",
```

2021-05-04 12:31 UTC, ruharen commented on src/code/translations/french.json
> +  "KEY_LIST2": "Liste des clées pour l'opération : {name}",
```suggestion
  "KEY_LIST2": "Liste des clées pour l'opération : {opName}",
```

2021-05-04 12:42 UTC, cloudkucooland commented on src/code/dialogs/blockersList.js
> +      title: wX("KNOWN_BLOCK", { name: operation.name }),
These all look good to me. I'll let LeJeu commit them as he reviews them.

2021-05-04 20:48 UTC, merged